version: '3.0'
services:
  bench:
    image: 'grafana/k6:master-with-browser'
    # afana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
    # ports:
      # - 3000:3000/tcp
    environment:
      - GT_URL=https://rdubrock.grafana.net
      - GT_USERNAME=hello@russdubrock.com
      - GT_PASSWORD=gxtPZsdw@qB2jEUomRRmBWraz
    volumes:
      - ./work/test/synthetics:/synthetics
    entrypoint: 'k6 run /synthetics/list-checks.js'

