# syntax=docker/dockerfile:1.4.2-labs

FROM golang:1.23-alpine AS builder

ARG BENCH_REVISION 
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG TARGETVARIANT
ENV GOOS=$TARGETOS GOARCH=$TARGETARCH
ARG FIXUID_VERSION=v0.6.0

RUN apk add --no-cache ca-certificates git

# build bench
WORKDIR /app

# go mod download first to cache modules for faster local builds
COPY go.mod go.sum ./
RUN --mount=type=cache,id=go-build-${TARGETOS}-${TARGETARCH}${TARGETVARIANT},target=/root/.cache/go-build \
  --mount=type=cache,id=go-pkg-${TARGETOS}-${TARGETARCH}${TARGETVARIANT},target=/go/pkg \
  CGO_ENABLED=0 \
  go mod download -x

# now copy the rest of the source and build
COPY bench.go ./bench.go
COPY cmd ./cmd
COPY pkg ./pkg

RUN CGO_ENABLED=0 go build \
  -ldflags="-X github.com/grafana/grafana-bench/pkg/revision.bench=${BENCH_REVISION}" \
  -trimpath -o build/grafana-bench .

# Install fixuid to allow setting the right uid when running local tests
RUN go get github.com/boxboat/fixuid@${FIXUID_VERSION} && \
  CGO_ENABLED=0 go build -o build/fixuid github.com/boxboat/fixuid

FROM grafana/k6:latest AS k6

# Use Playwright base image which includes all browser dependencies
FROM mcr.microsoft.com/playwright:v1.49.0-noble AS runtime

USER root

# Install additional system dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
  ca-certificates \
  git \
  wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Create bench user and group with known IDs
RUN groupadd -g 127 bench && \
  useradd --no-create-home --uid 1001 --gid 127 bench

# Configure fixuid to map the bench user to the uid:gid of the user invoking the image
RUN mkdir -p /etc/fixuid && \
  printf "user: bench\ngroup: bench\n" > /etc/fixuid/config.yml

# Copy binaries
COPY --from=k6 /usr/bin/k6 /usr/local/bin/k6
COPY --from=builder /app/build/grafana-bench /usr/local/bin/grafana-bench
COPY --from=builder /app/build/fixuid /usr/local/bin/
COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chown root:root /usr/local/bin/fixuid && \
  chmod 4755 /usr/local/bin/fixuid

# Set up working directory and permissions
WORKDIR /home/bench
RUN mkdir -p /home/bench/tests /home/bench/.cache && \
  chown -R bench:bench /home/bench

USER bench

# Call fixuid before calling bench to set the file permissions when running locally
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
