#! /usr/bin/env sh
TEST_TYPE=$1
echo TEST TYPE: $TEST_TYPE

echo K6 Project ID: $K6_CLOUD_PROJECT_ID
echo Grafana URL: $GRAFANA_URL
echo Grafana User: $GRAFANA_USER

# execute
grafana-bench $TEST_TYPE $GRAFANA_ADDRESS $GRAFANA_USER $GRAFANA_PASSWORD $GRAFANA_TEST_SUITE
