# syntax=docker/dockerfile:1.4.2-labs

FROM golang:1.25-alpine AS builder

ARG BENCH_REVISION 
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG TARGETVARIANT
ENV GOOS=$TARGETOS GOARCH=$TARGETARCH
ARG FIXUID_VERSION=v0.6.0

RUN apk add --no-cache ca-certificates git

# build bench
WORKDIR /app

# go mod download first to cache modules for faster local builds
COPY go.mod go.sum ./
RUN --mount=type=cache,id=go-build-${TARGETOS}-${TARGETARCH}${TARGETVARIANT},target=/root/.cache/go-build \
  --mount=type=cache,id=go-pkg-${TARGETOS}-${TARGETARCH}${TARGETVARIANT},target=/go/pkg \
  CGO_ENABLED=0 \
  go mod download -x

# now copy the rest of the source and build
COPY bench.go ./bench.go
COPY cmd ./cmd
COPY pkg ./pkg

RUN CGO_ENABLED=0 go build \
  -ldflags="-X github.com/grafana/grafana-bench/pkg/revision.bench=${BENCH_REVISION}" \
  -trimpath -o build/grafana-bench .

# Install fixuid for development builds
RUN go get github.com/boxboat/fixuid@${FIXUID_VERSION} && \
  CGO_ENABLED=0 go build -o build/fixuid github.com/boxboat/fixuid

FROM grafana/xk6:latest AS k6

# update this tag to the appropriate desired plugin version
RUN xk6 build --with github.com/grafana/xk6-grafana-alerting@a2ac37093f09d6bfc5c18202f9e15729584afce0

FROM alpine:3.22 AS runtime

USER root
RUN apk add --no-cache ca-certificates git wget

## add bench user and group with known group id and user id
RUN addgroup -g 127 bench && \
  adduser --disabled-password -u 1001 -G bench bench

# Copy binaries
COPY --from=k6 /xk6/k6 /usr/local/bin/k6
COPY --from=builder /app/build/grafana-bench /usr/local/bin/grafana-bench
COPY --from=builder /app/build/fixuid /usr/local/bin/fixuid
COPY docker-entrypoint-dev.sh /usr/local/bin/entrypoint.sh

# Configure fixuid for development
RUN mkdir -p /etc/fixuid && \
  printf "user: bench\ngroup: bench\npaths:\n  - /home/bench\n  - /tests\n  - /tmp\n" > /etc/fixuid/config.yml && \
  chown root:root /usr/local/bin/fixuid && \
  chmod 4755 /usr/local/bin/fixuid

# Create /tests directory as default test location
RUN mkdir -p /tests && chown -R bench:bench /tests

WORKDIR /tests

USER bench

# call fixuid before calling bench to set the file permissions when running locally
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
