#! /usr/bin/env sh
TEST_TYPE=$1

echo TEST_TYPE: $TEST_TYPE
echo K6_CLOUD_PROJECT_ID: $K6_CLOUD_PROJECT_ID
echo GRAFANA_ADDRESS: $GRAFANA_ADDRESS
echo GRAFAN_USER: $GRAFANA_USER
echo GRAFANA_TEST_SUITE: $GRAFANA_TEST_SUITE

# execute
grafana-bench $TEST_TYPE $GRAFANA_ADDRESS $GRAFANA_USER $GRAFANA_PASSWORD $GRAFANA_TEST_SUITE
