#! /usr/bin/env sh
if docker build --platform=linux/amd64 -t grafana-bench:latest .; then
  echo "build succeeded"
else
  echo "build failed"
  exit 1
fi





GCP_KEY_BASE64=$(cat creds/GCP-infra-manager-828bbfa6f427.json | base64 -b 0)
K6_CLOUD_PROJECT_ID=3653020
K6_CLOUD_TOKEN=$(cat creds/k6cloud_jefflevinslunch_grafana_net)
GRAFANA_VERSION="10.2.0-59489pre-0.1.357-8-gaeaf6eb4";

K6_PROMETHEUS_RW_USERNAME=531418
K6_PROMETHEUS_RW_PASSWORD=glc_eyJvIjoiNTgzNDgzIiwibiI6InN0YWNrLTQxNTMzNS1obS1rNi1wcm9tLXdyaXRlciIsImsiOiJtNDAyODVZNG9SN3VMYzZ5QXlndFkzYTEiLCJtIjp7InIiOiJ1cyJ9fQ==
K6_PROMETHEUS_RW_SERVER_URL=https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push

GRAFANA_URL=https://k6testinstant2.grafana-dev.net
GRAFANA_PORT=443;
GRAFANA_USER=k6user;
GRAFANA_PASSWORD=5B0u7Cr8g2ymcg==;
GRAFANA_TEST_SUITE=dashboards;

#GRAFANA_URL=jefflevinslunch.grafana.net;
#GRAFANA_PORT=443;
#GRAFANA_USER=admin;
#GRAFANA_PASSWORD=7092f20e3af11f3e0cb3d73f2a841ab2875021f2;
#GRAFANA_TEST_SUITE=dashboards

#docker run --rm --platform=linux/amd64 -e GCP_KEY_BASE64=$GCP_KEY_BASE64 \
#  -e K6_CLOUD_PROJECT_ID=$K6_CLOUD_PROJECT_ID \
#  -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN \
#  -e K6_PROMETHEUS_RW_USERNAME=$K6_PROMETHEUS_RW_USERNAME \
#  -e K6_PROMETHEUS_RW_PASSWORD=$K6_PROMETHEUS_RW_PASSWORD \
#  -e K6_PROMETHEUS_RW_SERVER_URL=$K6_PROMETHEUS_RW_SERVER_URL \
#  -e GRAFANA_TEST_REPO_URL=$GRAFANA_TEST_REPO_URL \
#  -e GRAFANA_VERSION=$GRAFANA_VERSION \
#  -e GRAFANA_URL=$GRAFANA_URL \
#  -e GRAFANA_PORT=$GRAFANA_PORT \
#  -e GRAFANA_USER=$GRAFANA_USER \
#  -e GRAFANA_PASSWORD=$GRAFANA_PASSWORD \
#  -e GRAFANA_TEST_SUITE=$GRAFANA_TEST_SUITE -it --entrypoint /bin/sh grafana-bench:latest

docker run --rm \
  --platform=linux/amd64 \
  -e GCP_KEY_BASE64=$GCP_KEY_BASE64 \
  -e K6_CLOUD_PROJECT_ID=$K6_CLOUD_PROJECT_ID \
  -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN \
  -e K6_PROMETHEUS_RW_USERNAME=$K6_PROMETHEUS_RW_USERNAME \
  -e K6_PROMETHEUS_RW_PASSWORD=$K6_PROMETHEUS_RW_PASSWORD \
  -e K6_PROMETHEUS_RW_SERVER_URL=$K6_PROMETHEUS_RW_SERVER_URL \
  -e GRAFANA_VERSION=$GRAFANA_VERSION \
  -e GRAFANA_URL=$GRAFANA_URL \
  -e GRAFANA_PORT=$GRAFANA_PORT \
  -e GRAFANA_USER=$GRAFANA_USER \
  -e GRAFANA_PASSWORD=$GRAFANA_PASSWORD \
  -e GRAFANA_TEST_SUITE=$GRAFANA_TEST_SUITE grafana-bench:latest

