trigger: "ci"

test:
  type: "smoke"
  runner: "playwright"

suite:
  name: "CI"
  path: "/home/bench/tests/CI/plugin-e2e"
  revision: "main"

grafana:
  url: "http://localhost:3000"
  admin:
    user: "admin"
    password: "admin"

pw:
  prepare: "yarn install; yarn playwright install"
  execute: "yarn run test"

log:
  level: DEBUG
