trigger: "ci"

test:
  type: "smoke"
  runner: "playwright"

suite:
  name: "CI"
  base: "/home/bench/tests/CI/plugin-e2e"

grafana:
  url: "http://localhost:3000"
  admin:
    user: "admin"
    password: "admin"

pw:
  prepare: "yarn install; yarn playwright install"
  execute: "yarn run test --grep-invert @performance"

prometheus:
  url: "https://prometheus-ops-03-ops-eu-south-0.grafana-ops.net/api/prom/push"
  user: 10428
# password provided as github action secret

log:
  level: DEBUG
