- name: Setup dependencies
  hosts: all
  gather_facts: no
  become: yes
  roles:
  - role: andrewrothstein.go-dev
  tasks:
    - name: Install git, make
      apt:
        pkg:
          - git
          - make
        state: latest
        update_cache: true
