name: test-bench-image

env:
  ENVIRONMENT: "prod"
  IMAGE_NAME: "grafana-bench"

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.x'

    - name: Set up k6
      run: go install go.k6.io/k6@latest

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

  test-container:
    runs-on: ubuntu-latest
    # run local registry that buildx can push to
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: build container
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BENCH_REVISION=${{ github.sha }}
          load: true
          tags: localhost:5000/grafana-bench-test:latest
      - name: check k6 browser
        run: |
          docker run --rm --entrypoint='' --volume="./CI/:/CI/" --volume="./screenshots:/home/bench/screenshots/" localhost:5000/grafana-bench-test:latest k6 run /CI/browser_test.js
      - name: archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots

  # publish container on build and test in main
  publish-main:
    # only publish on merge to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test-bench, test-container]
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: docker login (github)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jalevin # TODO don't use personal github
          password: ${{ secrets.JEFF_PAT }} # TODO don't use PAT
      - name: Docker Login (GCR)
        uses: docker/login-action@v3
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CONTAINERS_SA_JSON }}
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BENCH_REVISION=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/grafana/grafana-bench:latest
            us.gcr.io/kubernetes-dev/grafana-bench:latest

  publish-gar:
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test-bench, test-container]
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/shared-workflows/actions/push-to-gar-docker@main
        id: push-to-gar
        with:
          #registry: "<YOUR-GAR>" # e.g. us-docker.pkg.dev, optional
          image_name: grafana-bench
          tags: |-
            "latest"
          context: "." # e.g. "." - where the Dockerfile is
