name: test-bench-image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-pr-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: docker login (github)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jalevin # TODO don't use personal github
          password: ${{ secrets.JEFF_PAT }} # TODO don't use PAT
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # iidfile: grafana-bench.iid
          build-args: |
            BENCH_REVISION=${{ github.sha }}
          outputs: type=image,dest=/tmp/grafana-bench-image.tar
          #push: true
          tags: |
            grafana-bench:${{ github.sha }}
      - name: load and push container (github)
        run: |
          docker load --input /tmp/grafana-bench-image.tar
          docker buildx imagetools create \
            --tag ghcr.io/grafana/grafana-bench:${{ github.sha }} \
            grafana-bench:latest
      - name: upload bench image to artifact store
        uses: actions/upload-artifact@v3
        with:
          name: grafana_bench_image
          path: /tmp/grafana-bench-image.tar

        # run: docker build --platforms linux/amd64,linux/arm64,darwin/amd64 --iidfile=grafana-bench.iid --build-arg BENCH_REVISION=${{ github.sha }} .
      # - name: tag container
      #   run: |
      #     docker tag ghcr.io/grafana/grafana-bench:${{ github.sha }}
      #     docker push ghcr.io/grafana/grafana-bench:${{ github.sha }}

  test-pr-container:
    runs-on: ubuntu-latest
    needs: [build-pr-container]
    container:
      image: ghcr.io/grafana/grafana-bench:${{ github.sha }}
      env:
        GRAFANA_ADDRESS: PURPOSEFULLY_INVALID
        GRAFANA_USER: PURPOSEFULLY_INVALID
        GRAFANA_PASSWORD: PURPOSEFULLY_INVALID
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: run browser check
        run: |
          k6 run ./CI/browser_test.js
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots

  publish-main:
    runs-on: ubuntu-latest
    needs: [build-pr-container, test-pr-container]
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: docker login (github)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jalevin # TODO don't use personal github
          password: ${{ secrets.JEFF_PAT }} # TODO don't use PAT
      - name: Docker Login (GCR)
        uses: docker/login-action@v3
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CONTAINERS_SA_JSON }}
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with: 
          name: grafana_bench_image
          path: /tmp/grafana-bench-image.tar
      - name: Load image
        run: |
          docker load --input /tmp/grafana-bench-image.tar
      - name: Tag and push Docker images
        run: |
          docker buildx imagetools create \ 
            --tag ghcr.io/grafana/grafana-bench:latest \
            --tag us.gcr.io/kubernetes-dev/grafana-bench:latest \
            grafana-bench:${{ github.sha }}

          # labels: ${{ steps.meta.outputs.labels }}
      # - name: build
      #   run: docker build --iidfile=grafana-bench.iid --build-arg BENCH_REVISION=${{ github.sha }} . 
      # - name: tag
      #   run: |
      #     docker pull ghcr.io/grafana/grafana-bench:${{ github.sha }}
      #     docker tag $(cat grafana-bench.iid) us.gcr.io/kubernetes-dev/grafana-bench:latest
      #     echo us.gcr.io/kubernetes-dev/grafana-bench:latest > grafana-bench.tag
      # - name: push (GCR)
      #   if: github.ref == 'refs/heads/main'
      #   run: docker push $(cat grafana-bench.tag)
      # - name: docker Login (GHCR.io)
      #   env: 
      #     JEFF_PAT: ${{ secrets.JEFF_PAT }}
      #   run: |
      #     printf %s "$JEFF_PAT" | docker login -u jalevin --password-stdin https://ghcr.io
      # - name: push (GHCR.io)
      #   run: |
      #     docker tag $(cat grafana-bench.iid) ghcr.io/grafana/grafana-bench:latest
      #     docker push ghcr.io/grafana/grafana-bench:latest



      # TODO if branch is not main, delete container
      #- name: cleanup container if not in main branch
      #  if: ${{ github.ref_name}} != "main"
      #  run: |

      # TODO if branch main, ghcr.io/grafana/grafana-bench:latest
