name: docker-images

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login (GCR)
        env:
          GCP_CONTAINERS_SA_JSON: ${{ secrets.GCP_CONTAINERS_SA_JSON }}
        run: |
          printf %s "$GCP_CONTAINERS_SA_JSON" | docker login -u _json_key --password-stdin https://us.gcr.io
      - name: build
        run: docker build --iidfile=grafana-bench.iid --build-arg BENCH_REVISION=${{ github.sha }} . 
      - name: tag
        run: |
          docker tag $(cat grafana-bench.iid) us.gcr.io/kubernetes-dev/grafana-bench:latest
          echo us.gcr.io/kubernetes-dev/grafana-bench:latest > grafana-bench.tag
      - name: push
        if: github.ref == 'refs/heads/main'
        run: docker push $(cat grafana-bench.tag)
      - name: login to ghr.io
        env: 
          JEFF_PAT: ${{ secrets.JEFF_PAT }}
        run: |
          echo $JEFF_PAT | docker login ghcr.io -u jalevin --password-stdin
      - name: publish to GCR
        run: |
          docker tag $(cat grafana-bench.iid) ghcr.io/grafana/grafana-bench:latest
          docker push ghcr.io/grafana/grafana-bench:latest

