name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-docs.yml'
      - 'actions/build-techdocs/**'
      - 'actions/publish-techdocs/**'

jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@main
    secrets: inherit
    permissions:
      contents: read
    with:
      namespace: default
      kind: component
      name: grafana-bench
