name: Publish TechDocs
on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
  generate-docs:
    needs: "publish-docs"
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@main
    secrets: inherit
    with:
      namespace: default
      kind: component
      name: grafana-bench
