name: Measure frontend asset size

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'
  # Optional: Also allow manual triggering
  workflow_dispatch:

jobs:
  measure-frontend-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    #services:
    #  grafana:
    #    image: grafana/grafana:latest
    #    ports:
    #      - 3000:3000

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false

      - name: install bench
        run: go install

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: './CI/plugin-e2e/yarn.lock'

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: setup playwright
        #if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./CI/plugin-e2e
        run: |
          yarn install && yarn playwright install

      - name: run playwright tests
        working-directory: ./CI/plugin-e2e
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: /tmp/results.json
        run: yarn run test --grep @performance --reporter json

      #- name: cat results
      #  run: |
      #    cat /tmp/results.json
      #    cat /tmp/asset-metrics.txt

      #- id: get-secrets
      #  uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.2.0
      #  with:
      #    # Secrets placed in ci/repo/grafana/grafana-bench vault
      #    repo_secrets: |
      #      PROMETHEUS_PASSWORD=prometheus_token:prometheus_token

      - name: report result
        env:
          PROMETHEUS_URL: "https://prometheus-ops-03-ops-eu-south-0.grafana-ops.net/api/prom/push"
          PROMETHEUS_USER: 10428
          PROMETHEUS_PASSWORD: ${{ secrets.TEMP_PROMETHEUS_PASSWORD }}
        run: |
          grafana-bench report \
            --grafana-url "https://leeoniya.grafana.net" \
            --grafana-version "rrc-instant" \
            --test-suite-name "FrontendAssetSize" \
            --report-input playwright \
            --report-output log \
            --prometheus-metrics \
            --run-metrics-file "/tmp/asset-metrics.txt" \
            --log-level DEBUG \
            /tmp/results.json
