name: Manual Argo Trigger

on:
  workflow_dispatch:

jobs:
  trigger-argo-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Trigger grafana-bench-cd workflow
        uses: grafana/shared-workflows/actions/trigger-argo-workflow@ae92934a14a48b94494dbc06d74a81d47fe08a40
        with:
          instance: "ops"
          namespace: "grafana-bench-cd"
          workflow_template: "grafana-bench-cd"
          extra_args: "--wait --log"