name: manual libsonnet generation test

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'Target version to generate'
        required: true
        type: string

jobs:
  test-libsonnet-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      with:
        go-version-file: go.mod
        cache: false

    # TODO this is jalevin PAT. replace this with github app that can read deployment_tools repo
    - name: Get secrets from vault
      uses: grafana/shared-workflows/actions/get-vault-secrets@979bc5d3fd4ea82383d3f1362c34041687c74304
      with:
        repo_secrets: |
          DEPLOYMENT_TOOLS_TOKEN=temporary-github-pat:temporary-github-pat

    - name: Install dependencies
      run: make install-deps

    - name: Test full make libsonnet workflow
      env:
        GITHUB_TOKEN: ${{ env.DEPLOYMENT_TOOLS_TOKEN }}
        TARGET_VERSION: ${{ github.event.inputs.target_version }}
      run: |
        echo "Testing full make libsonnet-fetch workflow with TARGET_VERSION=$TARGET_VERSION"
        make libsonnet-fetch TARGET_VERSION="$TARGET_VERSION"
        ls libsonnet
        cat libsonnet/versions.libsonnet

