name: Create some bench logs for testing
# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 */3 * * *'
  # Optional: Also allow manual triggering
  workflow_dispatch:
jobs:
  generate-logs:
    runs-on: ubuntu-latest
    services:
      grafana:
        image: grafana/grafana:latest
        ports:
          - 3000:3000
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run playwright tests
        run: |
          docker run --rm \
            --network=host \
            --volume="./CI/:/home/bench/tests/CI/" \
            us-docker.pkg.dev/grafanalabs-dev/docker-grafana-bench-dev/grafana-bench:latest test \
            --config "/home/bench/tests/CI/playwright.yaml"
